Client server flow
FlunkyHD/sign-recognition pull request #11
Opened 2022-04-08 08:09 UTC by mKiddeT

Client is able to directly send video to the sanic backend api, and gets a response with the extracted landsmarks from mediapipe.

2022-04-08 08:36 UTC, CasperKjaerhus commented on nextjs/pages/components/WebcamCapture.tsx
> +        //a.click();
```suggestion
```

2022-04-08 08:36 UTC, CasperKjaerhus commented on nextjs/pages/components/WebcamCapture.tsx
> +import { json } from "stream/consumers";
```suggestion
```

2022-04-08 08:36 UTC, CasperKjaerhus commented on nextjs/pages/components/WebcamCapture.tsx
> +        var fd = new FormData();
```suggestion
        const fd = new FormData();
```

2022-04-08 08:36 UTC, CasperKjaerhus commented on nextjs/pages/index.tsx
> +        </div>
based css

2022-04-08 08:47 UTC, CasperKjaerhus approved these changes

2022-04-12 09:07 UTC, Deaxz requested changes

2022-04-12 09:07 UTC, Deaxz commented on nextjs/pages/components/WebcamCapture.tsx
>          document.body.appendChild(a);
Slet hele funktionalitet i stedet for delmængde
```suggestion
```

2022-04-12 09:16 UTC, Deaxz approved these changes

2022-04-12 09:20 UTC, merged