Docker setup sanic & nextjs
FlunkyHD/sign-recognition pull request #6
Opened 2022-03-24 10:18 UTC by CasperKjaerhus

2022-03-24 10:31 UTC, FlunkyHD approved these changes
Pretty good mr docker, dog lidt for meget farm med linje antal i commit.

2022-03-24 10:48 UTC, CasperKjaerhus commented
> Pretty good mr docker, dog lidt for meget farm med linje antal i commit.

Don't hate the player, hate the game

2022-03-24 10:53 UTC, Deaxz requested changes

2022-03-24 10:53 UTC, Deaxz commented on README.md
> +After docker compose has finished, nextjs should run on http://localhost and sanic should run on http://localhost:8080
nextjs kører vel på localhost:3000? og ikke bare localhost

2022-03-24 10:53 UTC, CasperKjaerhus commented on README.md
> +After docker compose has finished, nextjs should run on http://localhost and sanic should run on http://localhost:8080
> nextjs kører vel på localhost:3000? og ikke bare localhost

kig docker-compose, den kører port 3000 i containeren, men er exposed på port 80

2022-03-25 11:51 UTC, mKiddeT approved these changes
Dog shit code

2022-03-25 11:52 UTC, CasperKjaerhus commented
> Dog shit code

:( hvad blev der er "no u bad blyat"

2022-03-25 11:55 UTC, merged